[ART-2037] config:scan-sources: Detect changes in arches
openshift/doozer pull request #268
Opened 2020-08-26 15:18 UTC by joepvd

2020-08-31 07:08 UTC, vfreex requested changes

2020-08-31 07:08 UTC, vfreex commented on doozerlib/cli/__main__.py
> +                                needs_rebuild = True
After you reverting the change to rpm detection, we are good to merge this PR.

2020-08-31 07:24 UTC, joepvd commented
Reverted rpm commit. Will squash and merge after approval.

2020-09-01 01:36 UTC, vfreex commented
/lgtm

2020-09-01 01:37 UTC, vfreex approved these changes

2020-09-01 01:37 UTC, merged