add new field 'for_release' to individual files
openshift/doozer pull request #330
Opened 2020-11-18 13:14 UTC by shiywang

2020-12-07 05:55 UTC, vfreex requested changes
This should work. Just some minor issues otherwise LGTM.

2020-12-07 05:55 UTC, vfreex commented on doozerlib/cli/release_gen_payload.py
> +    def _get_non_release_images(self, images):
The function name doesn't seem to reflect what this function is doing. Could you give it a better name?

2020-12-07 05:55 UTC, vfreex commented on doozerlib/image.py
> +    def is_release(self):
Why is this property named `is_release` rather than `for_release`?

2020-12-08 13:48 UTC, sosiouxme commented
@shiywang I think @vfreex 's comments are on target, otherwise it LGTM. can we aim to merge after release work this week?

2020-12-10 08:40 UTC, vfreex commented
/lgtm

2020-12-10 08:41 UTC, vfreex approved these changes

2020-12-10 08:43 UTC, merged