Set assignees on ART alignment PRs
openshift/doozer pull request #358
Opened 2021-02-24 18:28 UTC by jupierce

2021-02-24 18:55 UTC, jupierce commented
@thegreyd thanks for bringing up the idea during the arch call!

2021-02-25 06:07 UTC, vfreex requested changes
generally LGTM, just 1 nit.

2021-02-25 11:08 UTC, thiagoalessio approved these changes
I also have the same question as Yuxiang about the duplicated line, but overall: /lgtm

2021-02-25 13:55 UTC, jupierce commented on doozerlib/cli/images_streams.py
> +            exectools.cmd_assert(f'git checkout public/{public_branch}')
If it's worth doing once, why not twice?  :)
Thanks for the review! Removed the line.

2021-02-25 14:03 UTC, merged