Prevent unnecessary clone to determine RPM package name
openshift/doozer pull request #423
Opened 2021-06-02 14:28 UTC by jupierce

2021-06-02 22:15 UTC, sosiouxme approved these changes

2021-06-02 22:15 UTC, sosiouxme commented on doozerlib/rpmcfg.py
> +        if default != -1:
this looks weird / non-pythonic... default ought to be `None` and this
```suggestion
        if default is not None:
```
but i guess this is everywhere and we can fix that some other time when it annoys me :)

2021-06-02 22:19 UTC, sosiouxme commented on doozerlib/rpmcfg.py
> +        raise IOError(f'Missing package name in RPM doozer metadata')
flake8 doesn't like this being an f-string.
Might be helpful to indicate which distgit has this problem though?

2021-06-03 03:44 UTC, vfreex approved these changes
Unit tests need to be fixed.

2021-06-03 03:44 UTC, vfreex requested changes
Unit tests need to be fixed.

2021-06-04 00:29 UTC, merged

2021-06-04 00:29 UTC, jupierce commented
Fixed the test.