ART-3050: add plashet from-tags --rhcos
openshift/doozer pull request #451
Opened 2021-06-28 09:56 UTC by vfreex

This PR adds `--rhcos` option to Plashet from-tags subverb.
When "--rhcos" argument is specified, the final list of package NVRs should include any dependencies specified in the assembly's assembly.rhcos.dependencies field.

2021-06-28 10:02 UTC, vfreex commented
@jupierce This PR is ready to review. I added a new function `assembly_rhcos_config` in `assembly.py` to handle `rhcos` field inheritance. Let me know if this is the desired behavior. Thank you in advance.

2021-06-30 18:44 UTC, jupierce requested changes
Just nits. Otherwise lgtm.

2021-06-30 18:44 UTC, jupierce commented on doozerlib/plashet.py
> +    def from_rhcos_deps(self, el_version: int, assembly: str, releases_config: Model, rpm_map: Dict[str, RPMMetadata]):
```suggestion
    def from_rhcos_deps(self, el_version: int, assembly: str, releases_config: Model, rpm_map: Dict[str, Dict]):
```
Just brew build dicts, right?

2021-06-30 18:44 UTC, jupierce commented on doozerlib/plashet.py
> +         :param rpm_map: Map of rpm_distgit_key -> RPMMetadata
```suggestion
        :param rpm_map: Map of rpm_distgit_key -> RPMMetadata
```

2021-06-30 18:47 UTC, jupierce commented
Going to go ahead and merge with tweaks. I would like to use `assembly_rhcos_config` in my next story.

2021-06-30 18:48 UTC, merged