art-2519 add check upstreampulls function
openshift/doozer pull request #488
Opened 2021-07-29 16:39 UTC by Ximinhan

add check upstreampulls function in doozer used by image-health check job to collect all opened pr of a target release.

2021-08-12 06:41 UTC, vfreex requested changes

2021-08-12 06:41 UTC, vfreex commented on doozerlib/cli/images_upstreampulls.py
> +github_token = os.getenv(constants.GIT_TOKEN)
Git != GitHub. There is no such thing called `GIT_TOKEN`. Would like to rename it to something like `GITHUB_TOKEN`.

2021-08-12 06:41 UTC, vfreex commented on doozerlib/cli/images_upstreampulls.py
> +@cli.command("images:upstreampulls", short_help="Check upstream PRs in open status")
It doesn't seem to me that the verb name `images:upstreampulls` or the help message explains well about what it  intends to do. Would like to have a better verb name like `images:streams prs list` for consistency and improved help message.

2021-08-12 06:41 UTC, vfreex commented on doozerlib/cli/images_upstreampulls.py
> +repo = github_client.get_repo("openshift/ocp-build-data")
`openshift/ocp-build-data` shouldn't be hardcoded here. How could I run the doozer with my own fork of ocp-build-data?

Global variables should be avoided as long as you can.

2021-08-12 06:41 UTC, vfreex commented on doozerlib/cli/images_upstreampulls.py
> +            xrepo = github_client.get_repo(upstream_project + "/" + upstream)
See https://github.com/openshift/doozer/blob/c7e31761b3ec312d4c3101bd3c93c94fc53c5025/doozerlib/cli/images_streams.py#L650 for how to correctly resolve the upstream repo url and branch for each image.

2021-08-12 06:41 UTC, vfreex commented on doozerlib/cli/images_upstreampulls.py
> +            if pr.user.login == "openshift-bot" and pr.base.ref == "release-" + version:
Please don't hardcode the login name and branch name.
login should be configurable, e.g. via command line option, and the branch name is not always follow `release-*`. There are exceptions.

2021-08-12 06:41 UTC, vfreex commented on doozerlib/cli/images_upstreampulls.py
> +                print("   {}".format(pr))
Use `yaml.dump`

2021-10-18 02:02 UTC, sosiouxme requested changes

2021-10-18 02:02 UTC, sosiouxme commented on doozerlib/cli/images_streams.py
> +                print("   {}".format(pr))
formatting yaml yourself is a recipe for disaster, how about just using the `yaml` module...

2021-11-02 21:57 UTC, sosiouxme commented
> ### Build #9
> ```
> Failed to build pygit2
> ERROR: Could not build wheels for pygit2 which use PEP 517 and cannot be installed directly
> ```

`git fetch && git rebase origin/master` should fix that up.

2021-11-02 22:13 UTC, sosiouxme approved these changes
looks good, will merge with one little change

2021-11-02 22:13 UTC, sosiouxme commented on doozerlib/cli/images_streams.py
> +@prs.command('list', short_help='List all open prs for upstream repo, run this need GITHUB_TOKEN var from env got set.')
I would reword a little bit shorter:
```suggestion
@prs.command('list', short_help='List all open prs for upstream repos (requires GITHUB_TOKEN env var to be set.')
```

2021-11-02 22:14 UTC, merged