[ART-4052] Allow override of `csv_namespace` per image
openshift/doozer pull request #604
Opened 2022-06-15 12:56 UTC by thiagoalessio

**WHY?**
We need to onboard some TELCO images that have references to images in non-openshift namespaces.

---

This change starts considering a new `csv_namespace` config present on the image, and uses its value when declared.
If not explicitly declared on the image config, it falls back to `group.yml`'s `csv_namespace` value.

Example:

Given the following image config snippet:
```yaml
update-csv:
  registry: foo.svc:5000
  namespace: bar
```

The image replacement in the CSV will become:
```
foo.svc:5000/bar/<image>
```

Relevant links:
* Related PR (adding this new option to ocp-build-data-validator): https://github.com/openshift/ocp-build-data-validator/pull/72
* Test run:
  * Image declaration: https://github.com/thiagoalessio/ocp-build-data/commit/f70fc08cd4dd11f08676f559cf6d48c94a02b90a
  * Custom build: https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fcustom/2542/parameters
    * Generated the following result in distgit: http://pkgs.devel.redhat.com/cgit/containers/topology-aware-lifecycle-operator/commit/manifests/stable/cluster-group-upgrades-operator.clusterserviceversion.yaml?h=rhaos-4.10-rhel-8&id=4eb1c05a261b4fdfaf85103db492d2333c6d9c28
    * _waiting for operator build, and bundle rebase+build_

2022-06-16 10:15 UTC, vfreex requested changes

2022-06-16 10:15 UTC, vfreex commented on doozerlib/distgit.py
> +        namespace = csv_config.get('csv_namespace', self.runtime.group_config.get('csv_namespace', None))
This doesn't seem to be correct. Here `namespace` will become be value for the operator that is being rebased. It should be relevant to the image that is referenced. So, it should be moved to the `for ref in image_refs` loop.

2022-06-16 10:25 UTC, vfreex commented on doozerlib/distgit.py
> +        namespace = csv_config.get('csv_namespace', self.runtime.group_config.get('csv_namespace', None))
Then namespace can be obtained from something like `meta.get("update-csv", {}).get("csv_namespace", group_csv_namespace)`

2022-06-24 02:03 UTC, vfreex commented
/hold
See discussion at https://coreos.slack.com/archives/GDBRP5YJH/p1655719622622219

2022-06-28 09:28 UTC, thiagoalessio commented
no longer needed, since ART-4052 is going to use "openshift" namespace after all.

2022-06-28 09:28 UTC, closed without merging